### ISSUE TITLE
Cannot read property 'inspect' of undefined

### ISSUE THREAD

**Issue by jfowler-imb** [codefresh-io/cli#360]
Hello, thanks for making the codefresh CLI. 

I am unable to run a simple pipeline and get this error when running. I am running with local volume and `--local` option. 

```
[SYSTEM]
 Message             Cannot read property 'inspect' of undefined
 Documentation Link  https://codefresh.io/docs/docs/codefresh-yaml/steps/freestyle/
 Name                TypeError
Pipeline executed successfully
```

## codefresh cli version
v0.33.0
```bash
$ codefresh version
client version: 0.33.0
```

## example codefresh.yml file

```yaml
version: '1.0'
stages:
  - prepare
  - context
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: github

  context:
    title: display pipeline context
    image: alpine
    stage: context
    commands:
      - echo CF_REVISION = ${CF_REVISION}
      - echo CF_REPO_OWNER = ${CF_REPO_OWNER}
      - echo CF_REPO_NAME = ${CF_REPO_NAME}
      - echo CF_BRANCH = ${CF_BRANCH}
      - echo CF_SHORT_REVISION = ${CF_SHORT_REVISION}
      - echo NAMESPACE = ${NAMESPACE}
```

## example codefresh cli `run` command with args
```bash
$ codefresh run my-project/my-pipeline \
  --local --local-volume -b feat/test-codefresh-run \
  -y .build/codefresh.yml -t my-trigger
```

I can run this pipeline without the error when run via the codefresh web UI. 

Thanks
